name 'chefvault_demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chefvault_demo'
long_description 'Installs/Configures chefvault_demo'
version '0.1.0'
